# Generated by Django 4.1.5 on 2023-04-05 14:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appusers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("appusers.useraccounts",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
